[package]
name = "claim-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "Dancu Sebastian",]

[dev-dependencies]

[dependencies.claim]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.34.1"
